version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v9m7i5p8
  build:
    commands:
      - echo Pulling the Docker image from ECR...
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG
#      - echo Tagging the Docker image..
#      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to ECS...
      - aws ecs update-service --cluster cluster-ahmed --service Service-1 --force-new-deployment
